language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER invoicify WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: YgPpluGpHl6hQ+TR50wIqD6KzTbWl/e1R0iQoUNmW+VJ1RqGPyP8vLr5YHOV/cGcawwrx03AUfi0KguBiXm9P3RRZS2TTURqd75aUHsU+u+UmeSLKaxL8P7vUSAXgYaRNHO5I/wFP17pq84NUbriyXO33us10v29h9xMaeTPr0Zmvn9AyjqmSxdMKznjb25wH4nGz9WF/7OvlQRllqtulDragfz9d/q7GJm7r2tS3AZgskmlIiFtltIqTMDnVZZxau/LPJZynwPOlvG5bOgTEZh1DgO9485V5F1/lGFilTFJD3YSAa8Ecr4EBykBlOG3Vf9InlQeoM4+2mS2CYt7T+dJmj4G1M3IP/4xlyFjVvNvCkF8mYtudTwJEkqUVN/vrmVCar2olv49+vm7JiF3JQoLOMq+oumLZvMWZQNXJFPdyXjJl2zkPQh10aVsGIoMnn61Ukun0WS2WbmWDxAod94hkup4dAoj6UjWW8mU8aH2RVJfBxRrFxaE5wY4Q6AaIylqXF63UNL+qjm8Vwu1XrU0fllElOZxOC8kq2dIM2Qx7YlQnWy/Ht1UUQSiaICBiQ0ChS60yqs3b2hEGqJg/TjxBhOSYe6IeNwzuA6eOOirKaoP0qssEfNFQsjzaJJlPBvYkOv5C0ectleivCylm8+Er3NjrhRlmt/HUx80dMU=
  app: peaceful-beach-99535
